spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boardrefactor
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 100
        one-indexed-parameters: true

custom:
  jwt:
    expiration-period: 3600000
    secret-key: dasf54we6+5f7414ae9wf87ergh9874h9rt7544y6fg4h6erh453418543412456dfsdfgw43t9072ysda